import '../materia.dart';

final ionsAquosos = Materia(
  'Íons em solução aquosa',
  'assets/images/iconesDeMateria/QuimiquITA_aquoso.png',
  [
    {
      'pergunta': 'Qual a cor do íon Cu\u00B2\u207A em solução aquosa?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Verde', 'Vermelho', 'Amarelo', 'Azul'],
      'correto': 3,
    },
    {
      'pergunta':
          'Qual a cor dos íons de metais representativos em solução aquosa?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Branco', 'Incolor', 'Amarelo', 'Azul'],
      'correto': 1,
    },
    {
      'pergunta': 'Qual a cor do íon Zn\u00B2\u207A em solução aquosa?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Branco', 'Incolor', 'Amarelo', 'Azul'],
      'correto': 1,
    },
    {
      'pergunta': 'Qual a cor do íon NO\u2083\u207B em solução aquosa?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': [ 'Incolor', 'Branco','Amarelo', 'Azul'],
      'correto': 0,
    },
    {
      'pergunta': 'Qual a cor do íon Ag\u207A em solução aquosa?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Amarelo', 'Vermelho', 'Incolor', 'Azul'],
      'correto': 2,
    },
    {
      'pergunta': 'Qual a cor do íon F\u207B em solução aquosa?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Amarelo', 'Vermelho', 'Incolor', 'Azul'],
      'correto': 2,
    },
    {
      'pergunta': 'Qual a cor do íon Cl\u207B em solução aquosa?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Incolor', 'Amarelo', 'Vermelho', 'Azul'],
      'correto': 0,
    },
    {
      'pergunta': 'Qual a cor do íon Br\u207B em solução aquosa?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Incolor', 'Amarelo', 'Vermelho', 'Azul'],
      'correto': 0,
    },
    {
      'pergunta': 'Qual a cor do íon I\u207B em solução aquosa?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Azul', 'Amarelo', 'Castanho', 'Incolor'],
      'correto': 3,
    },
    {
      'pergunta': 'Qual a cor do íon I\u2083\u207B em solução aquosa?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Azul', 'Amarelo', 'Castanho', 'Incolor'],
      'correto': 2,
    },
    {
      'pergunta': 'Qual a cor do íon Fe\u00B2\u207A em solução aquosa?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Amarelo', 'Verde', 'Laranja', 'Azul'],
      'correto': 1,
    },
    {
      'pergunta': 'Qual a cor do íon Fe\u00B3\u207A em solução aquosa?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Amarelo', 'Verde', 'Laranja', 'Marrom'],
      'correto': 3,
    },
    {
      'pergunta': 'Qual a cor do íon Ni\u00B2\u207A em solução aquosa?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Verde', 'Azul', 'Amarelo', 'Laranja'],
      'correto': 0,
    },
    {
      'pergunta': 'Qual a cor do íon Cr\u00B3\u207A em solução aquosa?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Vermelho', 'Verde', 'Violeta', 'Azul'],
      'correto': 1,
    },
    {
      'pergunta': 'Qual a cor do íon Mn\u00B2\u207A em solução aquosa?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Violeta', 'Rosa Pálido', 'Verde', 'Azul'],
      'correto': 1,
    },
    {
      'pergunta': 'Qual a cor do íon Co\u00B2\u207A em solução aquosa?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Amarelo', 'Marrom', 'Rosa', 'Azul'],
      'correto': 2,
    },
    {
      'pergunta': 'Qual a cor do íon MnO\u2084\u207B em solução aquosa?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Amarelo', 'Vermelho', 'Violeta', 'Azul'],
      'correto': 2,
    },
    {
      'pergunta': 'Qual a cor do íon CrO\u2084\u00B2\u207B em solução aquosa?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Vermelho', 'Amarelo', 'Verde', 'Azul'],
      'correto': 1,
    },
    {
      'pergunta':
          'Qual a cor do íon Cr\u2082O\u2087\u00B2\u207B em solução aquosa?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Amarelo', 'Vermelho', 'Azul', 'Laranja'],
      'correto': 3,
    },
    {
      'pergunta': 'Qual a cor do íon Ti\u00B3\u207A em solução aquosa?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Amarelo', 'Branco', 'Roxo', 'Azul'],
      'correto': 2,
    },
    {
      'pergunta': 'Qual a cor do íon V\u00B2\u207A em solução aquosa?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Lilás', 'Amarelo', 'Azul', 'Verde'],
      'correto': 0,
    },
    {
      'pergunta': 'Qual a cor do íon V\u00B3\u207A em solução aquosa?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Amarelo', 'Verde', 'Violeta', 'Azul'],
      'correto': 1,
    },
    {
      'pergunta': 'Qual a cor do íon Cr\u00B2\u207A em solução aquosa?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Amarelo', 'Verde', 'Roxo', 'Azul'],
      'correto': 3,
    },
    {
      'pergunta':
          'Qual a cor do íon complexo FeCl\u2084\u207B em solução aquosa?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Branco', 'Amarelo', 'Verde', 'Azul'],
      'correto': 1,
    },
    {
      'pergunta':
          'Qual a cor do íon complexo Cu(NH\u2083)\u2084\u00B2\u207A em solução aquosa?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Amarelo', 'Marrom', 'Verde', 'Azul'],
      'correto': 3,
    },
  ],
);
