import '../materia.dart';

final testeDeChama = Materia(
  'Teste de chama',
  'assets/images/iconesDeMateria/QuimiquITA_chama.png',
  [
    {
      'pergunta': 'Qual a cor obtida no teste de chama do Na\u207A?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Branco', 'Amarelo', 'Verde', 'Azul'],
      'correto': 1, // É o índice da resposta correta dentro do vetor
    },
    {
      'pergunta': 'Qual a cor obtida no teste de chama do Rb\u207A?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Vermelho', 'Magenta', 'Laranja', 'Azul'],
      'correto': 0,
    },
    {
      'pergunta': 'Qual a cor obtida no teste de chama do K\u207A?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Amarelo', 'Branco', 'Violeta', 'Azul'],
      'correto': 2,
    },
    {
      'pergunta': 'Qual a cor obtida no teste de chama do Mg?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Branco', 'Amarelo', 'Laranja', 'Vermelho'],
      'correto': 0,
    },
    {
      'pergunta': 'Qual a cor obtida no teste de chama do Ca\u00B2\u207A?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Verde', 'Azul', 'Branco', 'Laranja'],
      'correto': 3,
    },
    {
      'pergunta': 'Qual a cor obtida no teste de chama do Sr\u00B2\u207A?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Vermelho', 'Violeta', 'Amarelo', 'Azul'],
      'correto': 0,
    },
    {
      'pergunta': 'Qual a cor obtida no teste de chama do Ba\u00B2\u207A?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Vermelho', 'Laranja', 'Verde', 'Azul'],
      'correto': 2,
    },
    {
      'pergunta': 'Qual a cor obtida no teste de chama do Li\u207A?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Branco', 'Magenta', 'Verde', 'Azul'],
      'correto': 1,
    },
    {
      'pergunta': 'Qual a cor obtida no teste de chama do Pb\u00B2\u207A?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Amarelo', 'Magenta', 'Violeta', 'Azul'],
      'correto': 3,
    },
    {
      'pergunta': 'Qual a cor obtida no teste de chama do Zn\u00B2\u207A?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Branco', 'Amarelo', 'Verde', 'Azul'],
      'correto': 3,
    },
    {
      'pergunta': 'Qual a cor obtida no teste de chama do Cu\u00B2\u207A?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Amarelo', 'Laranja', 'Azul', 'Verde'],
      'correto': 3,
    },
    {
      'pergunta': 'Qual a cor obtida no teste de chama do Fe\u00B2\u207A?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Branco', 'Dourado', 'Laranja', 'Azul'],
      'correto': 1,
    },
    {
      'pergunta': 'Qual a cor obtida no teste de chama do Fe\u00B3\u207A?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Branco', 'Dourado', 'Laranja', 'Azul'],
      'correto': 1,
    },
    {
      'pergunta': 'Qual a cor obtida no teste de chama do Cs?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Branco', 'Amarelo', 'Azul', 'Violeta'],
      'correto': 2,
    },
    {
      'pergunta': 'Qual a cor obtida no teste de chama do Pb?',
      'tem imagem': false,
      'tem explicacao': false,
      'respostas': ['Branco', 'Laranja', 'Azul', 'Verde'],
      'correto': 0,
    },
  ],
);